---
title: "p8105_hw2_ss6692"
output: github_document
date: "2023-09-28"
---

## Problem 2

```{r load_libraries}
library(tidyverse)
library(readxl)
library(dplyr)
library(janitor)
```

### Loading and cleaning the Mr. Trash Wheel dataset

```{r clean_mr_trashwheel}
mr_trashweel = 
  readxl::read_excel("data/202207 Trash Wheel Collection Data.xlsx", range = "A2:N550", sheet = "Mr. Trash Wheel")|>
  janitor::clean_names() |>
  mutate(trashwheel = "mr_trashwheel")|>
  mutate(homes_powered = (weight_tons * 500)/30)|>
  select(-month, -year)
```

### Loading and cleaning the Professor Trash Wheel dataset

```{r clean_prof_trashwheel}
prof_trashwheel = 
  readxl::read_excel("data/202207 Trash Wheel Collection Data.xlsx", range = "A2:M97", sheet = "Professor Trash Wheel")|>
  janitor::clean_names() |>
  mutate(trashwheel = "professor") |>
  mutate(homes_powered = (weight_tons * 500)/30)|>
  select(-month, -year)
```

### Loading and cleaning the Gwynnda Trash Wheel dataset

```{r clean_gwynnda}
gwynnda = 
  readxl::read_excel("data/202207 Trash Wheel Collection Data.xlsx", range = "A2:K110", sheet = "Gwynnda Trash Wheel")|>
  janitor::clean_names() |>
  mutate(trashwheel = "gwynnda")|>
  mutate(homes_powered = (weight_tons * 500)/30)|>
  select(-month, -year)
```

### Merging the three datasets


